#服务端口配置
server:
  port: 8080
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #SQL日志输出配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#数据库链接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库地址可以根据需求更改
    url: jdbc:mysql://192.168.100.100:3306/webpro_db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Liu.201912
    #连接池配置
    druid:
      initialSize: 5 # 初始化连接数
      minIdle: 5 # 最小空闲连接数
      maxActive: 20 # 最大连接数
      maxWait: 60000 # 最大等待时间
      timeBetweenEvictionRunsMillis: 60000 # 连接空闲多久进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 连接在池中

logging:
  level:
    web: debug