#服务端口配置
server:
  port: 8080
#mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.ccst.endserver.mybatis.entity
#数据库链接配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库地址可以根据需求更改
    url: jdbc:mysql://192.168.100.100:3306/webpro_db?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Liu.201912